### ISSUE TITLE
Pattern match error results in disproportional error message

### ISSUE THREAD

**Issue by rvgast** [cwi-swat/rebel#14]
The following code:
`str lex(DefaultValue? d) {

        println(119);

        return "= <lex([e.val | DefaultValue? e := d])>";

    }`

Result in a pop up screen:
'Rascal parser' has encountered a problem. An internal error occurred during: "Rascal parser"

With error log: 
`org.rascalmpl.interpreter.asserts.ImplementationError: Unexpected error in Rascal interpreter: unexpected ambiguity: amb({appl(prod(label("match",sort("Expression")),[label("pattern",sort("Pattern")),layouts("LAYOUTLIST"),lit(":="),layouts("LAYOUTLIST"),label("expression",sort("Expression"))],{assoc(\non-assoc())}),[appl(prod(label("typedVariable",sort("Pattern")),[label("type",sort("Type")),layouts("LAYOUTLIST"),label("name",lex("Name"))],{}),[appl(prod(label("symbol",sort("Type")),[label("symbol",conditional(sort("Sym"),{except("labeled"),except("parametrized"),except("nonterminal"),except("parameter")}))],{}),[appl(prod(label("optional",sort("Sym")),[label("symbol",sort("Sym")),layouts("LAYOUTLIST"),lit("?")],{}),[appl(prod(label("nonterminal",sort("Sym")),[conditional(label("nonterminal",lex("Nonterminal")),{\not-follow(lit("["))})],{}),[appl(prod(lex("Nonterminal"),[conditional(seq([conditional(\char-class([range(65,90)]),{\not-precede(\char-class([range(65,90)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})]),{delete(keywords("RascalKeywords"))})],{}),[appl(regular(seq([conditional(\char-class([range(65,90)]),{\not-precede(\char-class([range(65,90)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})])),[char(68),appl(regular(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))),[char(101),char(102),char(97),char(117),char(108),char(116),char(86),char(97),char(108),char(117),char(101)])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7985,11,<158,27>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,12,<158,26>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,12,<158,26>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,12,<158,26>,<158,38>)],appl(prod(layouts("LAYOUTLIST"),[conditional(\iter-star(lex("LAYOUT")),{\not-follow(\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])),\not-follow(lit("//")),\not-follow(lit("/*"))})],{}),[appl(regular(\iter-star(lex("LAYOUT"))),[])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7996,0,<158,38>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7996,0,<158,38>,<158,38>)],appl(prod(lit("?"),[\char-class([range(63,63)])],{}),[char(63)])])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,13,<158,26>,<158,39>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,13,<158,26>,<158,39>)],appl(prod(layouts("LAYOUTLIST"),[conditional(\iter-star(lex("LAYOUT")),{\not-follow(\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])),\not-follow(lit("//")),\not-follow(lit("/*"))})],{}),[appl(regular(\iter-star(lex("LAYOUT"))),[appl(prod(lex("LAYOUT"),[\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])],{}),[char(32)])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7997,1,<158,39>,<158,40>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7997,1,<158,39>,<158,40>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7997,1,<158,39>,<158,40>)],appl(prod(lex("Name"),[conditional(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})]),{delete(keywords("RascalKeywords"))})],{}),[appl(regular(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})])),[char(101),appl(regular(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))),[])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7999,0,<158,41>,<158,41>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7998,1,<158,40>,<158,41>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7998,1,<158,40>,<158,41>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,15,<158,26>,<158,41>)],appl(prod(layouts("LAYOUTLIST"),[conditional(\iter-star(lex("LAYOUT")),{\not-follow(\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])),\not-follow(lit("//")),\not-follow(lit("/*"))})],{}),[appl(regular(\iter-star(lex("LAYOUT"))),[appl(prod(lex("LAYOUT"),[\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])],{}),[char(32)])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7999,1,<158,41>,<158,42>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7999,1,<158,41>,<158,42>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7999,1,<158,41>,<158,42>)],appl(prod(lit(":="),[\char-class([range(58,58)]),\char-class([range(61,61)])],{}),[char(58),char(61)]),appl(prod(layouts("LAYOUTLIST"),[conditional(\iter-star(lex("LAYOUT")),{\not-follow(\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])),\not-follow(lit("//")),\not-follow(lit("/*"))})],{}),[appl(regular(\iter-star(lex("LAYOUT"))),[appl(prod(lex("LAYOUT"),[\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])],{}),[char(32)])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8002,1,<158,44>,<158,45>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8002,1,<158,44>,<158,45>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8002,1,<158,44>,<158,45>)],appl(prod(label("qualifiedName",sort("Expression")),[label("qualifiedName",sort("QualifiedName"))],{}),[appl(prod(label("default",sort("QualifiedName")),[conditional(label("names",\iter-seps(lex("Name"),[layouts("LAYOUTLIST"),lit("::"),layouts("LAYOUTLIST")])),{\not-follow(lit("::"))})],{}),[appl(regular(\iter-seps(lex("Name"),[layouts("LAYOUTLIST"),lit("::"),layouts("LAYOUTLIST")])),[appl(prod(lex("Name"),[conditional(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})]),{delete(keywords("RascalKeywords"))})],{}),[appl(regular(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})])),[char(100),appl(regular(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))),[])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8004,0,<158,46>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,20,<158,26>,<158,46>)],appl(prod(label("ifDefinedOtherwise",sort("Expression")),[label("lhs",sort("Expression")),layouts("LAYOUTLIST"),lit("?"),layouts("LAYOUTLIST"),label("rhs",sort("Expression"))],{assoc(\non-assoc())}),[appl(prod(label("qualifiedName",sort("Expression")),[label("qualifiedName",sort("QualifiedName"))],{}),[appl(prod(label("default",sort("QualifiedName")),[conditional(label("names",\iter-seps(lex("Name"),[layouts("LAYOUTLIST"),lit("::"),layouts("LAYOUTLIST")])),{\not-follow(lit("::"))})],{}),[appl(regular(\iter-seps(lex("Name"),[layouts("LAYOUTLIST"),lit("::"),layouts("LAYOUTLIST")])),[appl(prod(lex("Name"),[conditional(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})]),{delete(keywords("RascalKeywords"))})],{}),[appl(regular(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})])),[char(68),appl(regular(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))),[char(101),char(102),char(97),char(117),char(108),char(116),char(86),char(97),char(108),char(117),char(101)])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7985,11,<158,27>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,12,<158,26>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,12,<158,26>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,12,<158,26>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,12,<158,26>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,12,<158,26>,<158,38>)],appl(prod(layouts("LAYOUTLIST"),[conditional(\iter-star(lex("LAYOUT")),{\not-follow(\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])),\not-follow(lit("//")),\not-follow(lit("/*"))})],{}),[appl(regular(\iter-star(lex("LAYOUT"))),[])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7996,0,<158,38>,<158,38>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7996,0,<158,38>,<158,38>)],appl(prod(lit("?"),[\char-class([range(63,63)])],{}),[char(63)]),appl(prod(layouts("LAYOUTLIST"),[conditional(\iter-star(lex("LAYOUT")),{\not-follow(\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])),\not-follow(lit("//")),\not-follow(lit("/*"))})],{}),[appl(regular(\iter-star(lex("LAYOUT"))),[appl(prod(lex("LAYOUT"),[\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])],{}),[char(32)])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7997,1,<158,39>,<158,40>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7997,1,<158,39>,<158,40>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7997,1,<158,39>,<158,40>)],appl(prod(label("match",sort("Expression")),[label("pattern",sort("Pattern")),layouts("LAYOUTLIST"),lit(":="),layouts("LAYOUTLIST"),label("expression",sort("Expression"))],{assoc(\non-assoc())}),[appl(prod(label("qualifiedName",sort("Pattern")),[label("qualifiedName",sort("QualifiedName"))],{}),[appl(prod(label("default",sort("QualifiedName")),[conditional(label("names",\iter-seps(lex("Name"),[layouts("LAYOUTLIST"),lit("::"),layouts("LAYOUTLIST")])),{\not-follow(lit("::"))})],{}),[appl(regular(\iter-seps(lex("Name"),[layouts("LAYOUTLIST"),lit("::"),layouts("LAYOUTLIST")])),[appl(prod(lex("Name"),[conditional(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})]),{delete(keywords("RascalKeywords"))})],{}),[appl(regular(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})])),[char(101),appl(regular(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))),[])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7999,0,<158,41>,<158,41>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7998,1,<158,40>,<158,41>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7998,1,<158,40>,<158,41>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7998,1,<158,40>,<158,41>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7998,1,<158,40>,<158,41>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7998,1,<158,40>,<158,41>)],appl(prod(layouts("LAYOUTLIST"),[conditional(\iter-star(lex("LAYOUT")),{\not-follow(\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])),\not-follow(lit("//")),\not-follow(lit("/*"))})],{}),[appl(regular(\iter-star(lex("LAYOUT"))),[appl(prod(lex("LAYOUT"),[\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])],{}),[char(32)])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7999,1,<158,41>,<158,42>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7999,1,<158,41>,<158,42>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7999,1,<158,41>,<158,42>)],appl(prod(lit(":="),[\char-class([range(58,58)]),\char-class([range(61,61)])],{}),[char(58),char(61)]),appl(prod(layouts("LAYOUTLIST"),[conditional(\iter-star(lex("LAYOUT")),{\not-follow(\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])),\not-follow(lit("//")),\not-follow(lit("/*"))})],{}),[appl(regular(\iter-star(lex("LAYOUT"))),[appl(prod(lex("LAYOUT"),[\char-class([range(9,13),range(32,32),range(133,133),range(160,160),range(5760,5760),range(6158,6158),range(8192,8202),range(8232,8233),range(8239,8239),range(8287,8287),range(12288,12288)])],{}),[char(32)])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8002,1,<158,44>,<158,45>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8002,1,<158,44>,<158,45>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8002,1,<158,44>,<158,45>)],appl(prod(label("qualifiedName",sort("Expression")),[label("qualifiedName",sort("QualifiedName"))],{}),[appl(prod(label("default",sort("QualifiedName")),[conditional(label("names",\iter-seps(lex("Name"),[layouts("LAYOUTLIST"),lit("::"),layouts("LAYOUTLIST")])),{\not-follow(lit("::"))})],{}),[appl(regular(\iter-seps(lex("Name"),[layouts("LAYOUTLIST"),lit("::"),layouts("LAYOUTLIST")])),[appl(prod(lex("Name"),[conditional(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})]),{delete(keywords("RascalKeywords"))})],{}),[appl(regular(seq([conditional(\char-class([range(65,90),range(95,95),range(97,122)]),{\not-precede(\char-class([range(65,90),range(95,95),range(97,122)]))}),conditional(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)])),{\not-follow(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))})])),[char(100),appl(regular(\iter-star(\char-class([range(48,57),range(65,90),range(95,95),range(97,122)]))),[])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8004,0,<158,46>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(8003,1,<158,45>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7998,6,<158,40>,<158,46>)]])[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,20,<158,26>,<158,46>)]})[@loc=|project://ing-rebel-generators/src/gen/documentation/docgen/Iteration1.rsc|(7984,20,<158,26>,<158,46>)]
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAmb(Import.java:509)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:34)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import$1.visitTreeAppl(Import.java:488)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:32)
	at org.rascalmpl.values.uptr.visitors.TreeVisitor.visitConstructor(TreeVisitor.java:24)
	at org.rascalmpl.value.impl.AnnotatedConstructorFacade.accept(AnnotatedConstructorFacade.java:41)
	at org.rascalmpl.semantics.dynamic.Import.parseFragments(Import.java:473)
	at org.rascalmpl.semantics.dynamic.Import.parseModuleAndFragments(Import.java:438)
	at org.rascalmpl.interpreter.Evaluator.parseModuleAndFragments(Evaluator.java:1391)
	at org.rascalmpl.eclipse.editor.ParseController$ParseJob.run(ParseController.java:208)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

**Comment by rvgast** [comment]
Issue moved to: 
https://github.com/usethesource/rascal/issues/998
